import Foundation
import CoreFoundation
import Observation
import WebKit

/// The production implementation owns a fresh, nonpersistent WebKit context.
/// Tests inject this seam without starting a browser or contacting the service.
@MainActor
protocol SodaLoginSessionBackend: AnyObject {
    var webView: WKWebView? { get }
    func prepare() async throws
    func send(_ request: URLRequest) async throws -> (Data, HTTPURLResponse)
    func snapshotCookies() async throws -> [MusicSessionCookie]
    func cancel()
}

struct SodaQRCode: Sendable, Equatable {
    let scanURL: URL
    let expiresAt: Date
}

enum SodaLoginPhase: Sendable, Equatable {
    case idle, creating, waiting, scanned, throttled, verifying, connected, expired, failed, cancelled
}

/// Each attempt uses its own official web runtime and browser cookie store.
/// Ambient browser cookies and device credentials are never imported.
@MainActor @Observable
final class SodaQRAuthentication {
    private(set) var phase: SodaLoginPhase = .idle
    private(set) var challenge: SodaQRCode?
    private(set) var message = "正在获取二维码…"
    private(set) var pollInterval: TimeInterval = 2.5
    private var token = ""
    private var portrait = ""
    private var traceID = ""
    private var cookieJar: [MusicSessionCookie] = []
    private var generation = UUID()
    private var lastPollAt: Date?
    private var throttleCount = 0
    private var browserSession: (any SodaLoginSessionBackend)?
    private var attemptDeadline: Date?
    private let fixtureTransport: NativeMusicHTTP.Transport?
    private let browserFactory: @MainActor () -> any SodaLoginSessionBackend
    private let now: @MainActor () -> Date

    var webView: WKWebView? { browserSession?.webView }

    init(transport: NativeMusicHTTP.Transport? = nil,
         browserFactory: (@MainActor () -> any SodaLoginSessionBackend)? = nil,
         now: @escaping @MainActor () -> Date = { Date() }) {
        self.fixtureTransport = transport
        self.browserFactory = browserFactory ?? { SodaWebLoginSession() }
        self.now = now
    }

    private static let api = URL(string: "https://api.qishui.com")!
    private static let redirectHosts: Set<String> = ["api.qishui.com", "bff-pc.qishui.com"]
    private static let sessionNames: Set<String> = ["sessionid", "sessionid_ss"]
    private static let common = [
        "passport_jssdk_version": "2.4.13", "passport_jssdk_type": "normal",
        "p_js_v": "2.4.13", "p_js_t": "pro", "p_ver": "1.0.29",
        "account_sdk_source": "web", "language": "zh",
        "is_from_ttaccountsdk": "1", "aid": "386088", "is_from_iesaccountsaas": "1", "is_new_login": "1",
        "device_platform": "PC", "version_code": "3.7.0"
    ]

    @discardableResult
    func create() async throws -> SodaQRCode {
        try Task.checkCancellation()
        cancel()
        let attempt = generation
        let started = now()
        attemptDeadline = started.addingTimeInterval(180)
        // An attempt correlation ID generated by this app, not a borrowed
        // account/device identity or a client signature.
        portrait = UUID().uuidString.lowercased() + ".login"
        traceID = String(UUID().uuidString.prefix(8)).lowercased()
        phase = .creating; message = "正在获取二维码…"
        do {
            if fixtureTransport == nil {
                let session = browserFactory()
                // Assign before prepare so the sheet can mount the real view.
                browserSession = session
                message = "正在准备汽水音乐登录…"
                try await session.prepare()
                try ensurePending(attempt)
                try checkDeadline()
            }
            message = "正在获取二维码…"
            var query = attemptQuery
            query.merge(["next": Self.api.absoluteString, "need_logo": "false", "need_short_url": "false", "is_new_login": "1"]) { _, new in new }
            let request = Self.request(path: "/passport/web/get_qrcode/", query: query)
            let (data, response) = try await send(request, attempt: attempt)
            try checkHTTP(response)
            let payload = try Self.payload(data)
            try checkBusiness(payload, stage: "获取二维码")
            guard let value = payload.fields["token"] as? String, !value.isEmpty, value.utf8.count <= 4096,
                  let scan = payload.fields["qrcode_index_url"] as? String, scan.utf8.count <= 8192,
                  let url = URL(string: scan), Self.allowedRedirect(url),
                  let scanURL = Self.currentPCScanURL(from: url, token: value) else {
                throw MusicError.message("汽水音乐未返回有效二维码，请重新获取。")
            }
            let upstreamExpiry = Self.number(payload.fields["expire_time"]).map { Date(timeIntervalSince1970: $0) }
            let deadline = min(upstreamExpiry ?? started.addingTimeInterval(180), started.addingTimeInterval(180))
            guard deadline > now() else { throw MusicError.message("汽水音乐返回的二维码已过期，请重新获取。") }
            attemptDeadline = deadline
            token = value
            let code = SodaQRCode(scanURL: scanURL, expiresAt: deadline)
            challenge = code; phase = .waiting; pollInterval = 2.5
            message = "在汽水音乐 App 打开「搜索」，点击搜索框右侧「扫一扫」，并在手机上确认。"
            return code
        } catch {
            try ensureActive(attempt)
            try expireIfDeadlinePassed()
            if phase != .expired { fail(error.localizedDescription) }
            throw error
        }
    }

    /// Returns cookies only after the server confirms this particular QR code.
    /// The caller must validate the platform profile before marking success.
    func poll() async throws -> [MusicSessionCookie]? {
        let attempt = generation
        guard let challenge, !token.isEmpty,
              [.waiting, .scanned, .throttled].contains(phase) else { return nil }
        guard now() < challenge.expiresAt else {
            expire()
            throw MusicError.message(message)
        }
        if let lastPollAt, now().timeIntervalSince(lastPollAt) < pollInterval { return nil }
        lastPollAt = now()
        do {
            var request = Self.request(path: "/passport/web/check_qrconnect/", query: attemptQuery)
            request.httpMethod = "POST"
            request.setValue("application/x-www-form-urlencoded", forHTTPHeaderField: "Content-Type")
            request.httpBody = Self.form([
                "need_logo": "false", "need_short_url": "false", "is_frontier": "true",
                "token": token, "is_new_login": "1", "next": Self.api.absoluteString
            ])
            let (data, response) = try await send(request, attempt: attempt)
            guard now() < challenge.expiresAt else {
                expire()
                throw MusicError.message(message)
            }
            if response.statusCode == 429 { try throttled(code: "HTTP 429"); return nil }
            try checkHTTP(response)
            let payload = try Self.payload(data)
            let errorCode = payload.errorCode
            if errorCode == 7 { try throttled(code: "错误 7"); return nil }
            if errorCode == 2046 {
                throw MusicError.message("抖音要求二次身份验证（错误 2046）。当前扫码接入无法完成这一步；请先在官方汽水音乐客户端完成验证，再重新扫码。")
            }
            let status = Self.status(payload.fields["status"])
            if errorCode == 2 {
                expire()
                throw MusicError.message(message)
            }
            try checkBusiness(payload, stage: "扫码确认")
            if ["expired", "expire", "4"].contains(status) {
                expire()
                throw MusicError.message(message)
            }
            throttleCount = 0; pollInterval = 2.5
            switch status {
            case "new", "1": phase = .waiting; message = "在汽水音乐 App 打开「搜索」，点击搜索框右侧「扫一扫」，并在手机上确认。"
            case "scanned", "2": phase = .scanned; message = "已扫码，请在手机上确认登录。"
            case "confirmed", "success", "3":
                try ensurePending(attempt)
                var callback: URL?
                if let redirect = payload.fields["redirect_url"] as? String, !redirect.isEmpty {
                    guard let url = URL(string: redirect), Self.allowedRedirect(url) else {
                        throw MusicError.message("汽水音乐返回了不受信任的登录回调，已停止连接。")
                    }
                    callback = url
                }
                let cookies = DirectMusicAccess.sessionCookies(cookieJar, for: .soda)
                let profileURL = Self.api.appending(path: "luna/pc/me")
                guard cookies.contains(where: { Self.sessionNames.contains($0.name) && $0.matches(profileURL, now: now()) }) else {
                    if let url = callback {
                        if url.host?.lowercased() != Self.api.host {
                            throw MusicError.message("手机已确认，但汽水音乐要求跨域登录回调，当前网页接入暂未支持这一步。请关闭后重试，或使用官方客户端。")
                        }
                        throw MusicError.message("手机已确认，但汽水音乐未返回有效会话，当前网页接入暂未支持该登录回调。请关闭后重试，或使用官方客户端。")
                    }
                    throw MusicError.message("手机已确认，但汽水音乐未向本次扫码返回有效会话。请重新获取二维码；当前接口可能要求官方浏览器验证。")
                }
                // The official PC callback resolves success without an extra
                // exchange. A real browser session must pass profile validation.
                phase = .verifying; message = "正在验证汽水音乐账号…"
                return cookies
            case "refused", "5":
                throw MusicError.message("本次扫码登录已取消，请重新获取二维码。")
            default:
                throw MusicError.message("汽水音乐返回了无法识别的扫码状态，请重新获取二维码。")
            }
            return nil
        } catch {
            try ensureActive(attempt)
            try expireIfDeadlinePassed()
            if phase != .expired { fail(error.localizedDescription) }
            throw error
        }
    }

    func validate(_ cookies: [MusicSessionCookie], onConnect: @MainActor ([MusicSessionCookie]) async throws -> Void) async throws {
        let attempt = generation
        guard phase == .verifying else { throw CancellationError() }
        do {
            try ensureActive(attempt)
            try await onConnect(cookies)
            try ensurePending(attempt)
            phase = .connected; message = "已连接汽水音乐"
            closeContext()
        } catch {
            try ensureActive(attempt)
            if phase != .expired { fail(error.localizedDescription) }
            throw error
        }
    }

    func cancel() {
        generation = UUID()
        closeContext()
        lastPollAt = nil; throttleCount = 0; pollInterval = 2.5
        phase = .cancelled
    }

    func fail(_ reason: String) {
        phase = .failed; message = reason
        closeContext()
    }

    private func expire() {
        phase = .expired; message = "二维码已过期，请重新获取。"
        closeContext()
    }

    private func closeContext() {
        browserSession?.cancel()
        browserSession = nil
        token = ""; portrait = ""; traceID = ""; cookieJar = []; challenge = nil
        attemptDeadline = nil
    }

    private func checkDeadline() throws {
        guard let attemptDeadline, now() < attemptDeadline else {
            expire()
            throw MusicError.message(message)
        }
    }

    private func expireIfDeadlinePassed() throws {
        guard let attemptDeadline, now() >= attemptDeadline else { return }
        expire()
        throw MusicError.message(message)
    }

    private func ensureActive(_ attempt: UUID) throws {
        try Task.checkCancellation()
        guard generation == attempt, phase != .cancelled else { throw CancellationError() }
    }

    private func ensurePending(_ attempt: UUID) throws {
        try ensureActive(attempt)
        guard ![.failed, .expired, .connected].contains(phase) else { throw CancellationError() }
    }

    private func throttled(code: String) throws {
        throttleCount += 1
        guard throttleCount <= 3 else {
            throw MusicError.message("汽水音乐扫码接口持续限流（\(code)），已停止重试。请稍后重新获取二维码。")
        }
        phase = .throttled; pollInterval = 5
        message = "汽水音乐暂时限流（\(code)），5 秒后重试（\(throttleCount)/3）。"
    }

    private func checkHTTP(_ response: HTTPURLResponse) throws {
        guard (200..<300).contains(response.statusCode) else {
            throw MusicError.message("汽水音乐登录请求未完成（HTTP \(response.statusCode)），请重新获取二维码。")
        }
    }

    private func checkBusiness(_ payload: LoginPayload, stage: String) throws {
        guard payload.errorCode != 0 || payload.wrapperFailure else { return }
        if payload.errorCode == 2046 {
            throw MusicError.message("抖音要求二次身份验证（错误 2046）。请先在官方汽水音乐客户端完成验证，再重新扫码。")
        }
        let details = safePlatformDescription(payload)
        let explanation = details.map { "平台说明：\($0)" } ?? "平台未提供具体原因。"
        let codeLabel = payload.errorCode == 0 ? "" : "（错误 \(payload.errorCode)）"
        throw MusicError.message("汽水音乐未完成\(stage)\(codeLabel)。\(explanation)\n请重新获取二维码。")
    }

    /// Show only a bounded, scrubbed human-readable platform explanation. Do
    /// not expose raw response JSON, URLs, QR tokens or account credentials.
    private func safePlatformDescription(_ payload: LoginPayload) -> String? {
        var secrets = [token] + cookieJar.map(\.value)
        secrets.append(contentsOf: payload.secrets)
        for raw in payload.descriptions {
            var text = String(raw.prefix(4096))
            for secret in secrets.filter({ !$0.isEmpty }).sorted(by: { $0.count > $1.count }) {
                text = text.replacingOccurrences(of: secret, with: "[已隐藏]")
            }
            for pattern in [
                #"(?i)https?://[^\s<>"'，。；（）]+"#,
                #"(?i)(?:token|sessionid(?:_ss)?|csrf|cookie|signature|ticket|password)\s*[:=]\s*[^\s，。；]+"#,
                #"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}"#,
                #"(?<![0-9])(?:\+?86[- ]?)?1[3-9][0-9]{9}(?![0-9])"#,
                #"[A-Za-z0-9_+/=-]{24,}"#
            ] {
                text = text.replacingOccurrences(of: pattern, with: "[已隐藏]", options: .regularExpression)
            }
            text = String(text.unicodeScalars.map { CharacterSet.controlCharacters.contains($0) ? " " : String($0) }.joined())
            text = text.split(whereSeparator: \.isWhitespace).joined(separator: " ")
            guard !text.isEmpty, !["success", "ok", "successful", "error", "fail", "failed", "failure"].contains(text.lowercased()) else { continue }
            return String(text.prefix(220))
        }
        return nil
    }

    private func send(_ input: URLRequest, attempt: UUID) async throws -> (Data, HTTPURLResponse) {
        try ensurePending(attempt)
        try checkDeadline()
        guard let url = input.url, Self.allowedRedirect(url), url.host?.lowercased() == Self.api.host,
              url.path.hasPrefix("/passport/") else { throw MusicError.message("已阻止非官方登录请求。") }
        var request = input
        request.httpShouldHandleCookies = false
        request.cachePolicy = .reloadIgnoringLocalCacheData
        if let attemptDeadline {
            request.timeoutInterval = min(15, max(0.1, attemptDeadline.timeIntervalSince(now())))
        }
        let matching = cookieJar.filter { $0.matches(url, now: now()) }.sorted { $0.path.count > $1.path.count }
        // Only the fixture transport consumes explicit cookies. Production
        // fetch owns credentials and CSRF inside the isolated browser context.
        if fixtureTransport != nil {
            request.setValue(matching.isEmpty ? nil : matching.map { "\($0.name)=\($0.value)" }.joined(separator: "; "), forHTTPHeaderField: "Cookie")
            let csrf = matching.first { $0.name == "passport_csrf_token" && !$0.value.isEmpty } ??
                matching.first { $0.name == "passport_csrf_token_default" && !$0.value.isEmpty }
            request.setValue(csrf?.value ?? "", forHTTPHeaderField: "x-tt-passport-csrf-token")
        } else {
            request.setValue(nil, forHTTPHeaderField: "Cookie")
            request.setValue(nil, forHTTPHeaderField: "x-tt-passport-csrf-token")
        }
        request.setValue(portrait.isEmpty ? nil : portrait, forHTTPHeaderField: "x-tt-passport-verify-portrait")
        request.setValue(traceID.isEmpty ? nil : traceID, forHTTPHeaderField: "x-tt-passport-trace-id")
        request.setValue("application/json, text/javascript", forHTTPHeaderField: "Accept")
        let result: (Data, HTTPURLResponse)
        if let fixtureTransport {
            result = try await fixtureTransport(request)
        } else {
            guard let browserSession else { throw MusicError.message("汽水音乐登录页面已关闭，请重新获取二维码。") }
            result = try await browserSession.send(request)
        }
        try ensurePending(attempt)
        try checkDeadline()
        let (data, response) = result
        guard data.count <= 512 * 1024, response.url?.scheme == "https", response.url?.host?.lowercased() == url.host?.lowercased(),
              response.url?.path == url.path else { throw MusicError.message("汽水音乐登录响应无效，已停止连接。") }
        if fixtureTransport != nil {
            receiveFixtureCookies(response, url: url)
        } else {
            guard let browserSession else { throw CancellationError() }
            let snapshot = try await browserSession.snapshotCookies()
            try ensurePending(attempt)
            try checkDeadline()
            // Browser state is authoritative, including expired/deleted entries.
            // Never manufacture Set-Cookie headers from JavaScript response data.
            cookieJar = snapshot.filter { Self.validCookie($0, origin: url.host ?? "") && ($0.expires.map { $0 > now() } ?? true) }
        }
        return (data, response)
    }

    /// Explicitly injected fixture transports model real Set-Cookie responses;
    /// the production WebKit transport never passes through this importer.
    private func receiveFixtureCookies(_ response: HTTPURLResponse, url: URL) {
        let fields = response.allHeaderFields.reduce(into: [String: String]()) { result, field in
            guard let key = field.key as? String else { return }
            result[key] = String(describing: field.value)
        }
        let received = HTTPCookie.cookies(withResponseHeaderFields: fields, for: url)
        for rawCookie in received {
            let cookie = MusicSessionCookie(rawCookie)
            let domain = Self.normalizedDomain(cookie.domain)
            guard Self.validCookie(cookie, origin: url.host ?? "") else { continue }
            // A response can set a cookie for a later endpoint's Path. Path and
            // expiry are checked on sending; deletion still removes the jar entry.
            cookieJar.removeAll { $0.name == cookie.name && Self.normalizedDomain($0.domain) == domain && $0.path == cookie.path }
            let maxAge = Self.number(rawCookie.properties?[.maximumAge])
            if (cookie.expires.map({ $0 <= now() }) ?? false) || (maxAge.map({ $0 <= 0 }) ?? false) { continue }
            cookieJar.append(cookie)
        }
    }

    private static func validCookie(_ cookie: MusicSessionCookie, origin: String) -> Bool {
        let domain = normalizedDomain(cookie.domain)
        let host = origin.lowercased()
        return ["qishui.com", "api.qishui.com", "bff-pc.qishui.com"].contains(domain) &&
            (host == domain || host.hasSuffix("." + domain)) &&
            cookie.path.hasPrefix("/") && cookie.path.utf8.count <= 4096 &&
            cookie.value.utf8.count <= 16384 && !cookie.name.isEmpty && cookie.name.utf8.count <= 1024 &&
            !cookie.name.contains(where: { $0.isWhitespace || $0 == ";" || $0 == "=" }) &&
            !cookie.value.unicodeScalars.contains(where: { $0.value < 0x20 || $0.value == 0x7F || $0.value == 0x3B })
    }

    static func allowedRedirect(_ url: URL) -> Bool {
        url.scheme?.lowercased() == "https" && url.user == nil && url.password == nil &&
            (url.port == nil || url.port == 443) && redirectHosts.contains(url.host?.lowercased() ?? "")
    }

    /// The current official PC client supplies its own phone H5 target instead
    /// of displaying the generic account SDK QR. Use only the returned token;
    /// do not import the official implementation or disclose the computer name.
    private static func currentPCScanURL(from officialURL: URL, token: String) -> URL? {
        guard let official = URLComponents(url: officialURL, resolvingAgainstBaseURL: false),
              let values = official.queryItems else { return nil }
        let tokens = values.filter { $0.name == "token" }
        guard tokens.count == 1, tokens[0].value == token else { return nil }
        var target = URLComponents(string: "https://bff-pc.qishui.com/light/invoke/scan_login")!
        target.queryItems = [
            URLQueryItem(name: "token", value: token), URLQueryItem(name: "os", value: "Mac"),
            URLQueryItem(name: "computer_name", value: "AlpacaMusic")
        ]
        return target.url
    }

    private var attemptQuery: [String: String] {
        var query = Self.common
        query["biz_trace_id"] = traceID
        return query
    }

    private static func request(path: String, query: [String: String]) -> URLRequest {
        var components = URLComponents(url: api.appending(path: path), resolvingAgainstBaseURL: false)!
        components.queryItems = query.sorted { $0.key < $1.key }.map { URLQueryItem(name: $0.key, value: $0.value) }
        return URLRequest(url: components.url!, timeoutInterval: 15)
    }

    private static func form(_ values: [String: String]) -> Data {
        let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "-._~"))
        return Data(values.sorted { $0.key < $1.key }.map {
            "\($0.key.addingPercentEncoding(withAllowedCharacters: allowed) ?? "")=\($0.value.addingPercentEncoding(withAllowedCharacters: allowed) ?? "")"
        }.joined(separator: "&").utf8)
    }

    private struct LoginPayload {
        let fields: [String: Any]
        let errorCode: Int
        let wrapperFailure: Bool
        let descriptions: [String]
        let secrets: [String]
    }

    private static func payload(_ data: Data) throws -> LoginPayload {
        guard let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            throw MusicError.message("汽水音乐未返回有效登录数据，请重新获取二维码。")
        }
        let wrapped = root["data"] as? [String: Any]
        let fields = wrapped ?? root
        // The actual official SDK resolves a data envelope only when its
        // message is success. Preserve raw/unwrapped responses too.
        let wrapperFailure = wrapped != nil && root["message"] != nil && (root["message"] as? String)?.lowercased() != "success"
        // An outer failure cannot be overwritten by an inner success. Validate
        // both present codes, including malformed huge/boolean/null values.
        let outerCode = try businessCode(root)
        let innerCode = try businessCode(fields)
        let errorCode = outerCode != 0 ? outerCode : innerCode
        let explanationSources = outerCode != 0 || wrapperFailure ? [root, fields] : [fields, root]
        let descriptions = explanationSources.flatMap { value in
            ["description", "message", "error_message"].compactMap { value[$0] as? String }
        }
        let secrets = [root, fields].flatMap { value in
            value.compactMap { key, raw -> String? in
                guard ["token", "session", "cookie", "password", "signature", "ticket"].contains(where: { key.lowercased().contains($0) }),
                      let secret = raw as? String, !secret.isEmpty, secret.utf8.count <= 16384 else { return nil }
                return secret
            }
        }
        return LoginPayload(fields: fields, errorCode: errorCode, wrapperFailure: wrapperFailure, descriptions: descriptions, secrets: secrets)
    }

    private static func normalizedDomain(_ domain: String) -> String {
        domain.lowercased().trimmingCharacters(in: CharacterSet(charactersIn: "."))
    }
    private static func number(_ value: Any?) -> Double? {
        if let number = value as? NSNumber { return number.doubleValue.isFinite ? number.doubleValue : nil }
        if let text = value as? String, let number = Double(text), number.isFinite { return number }
        return nil
    }
    /// Never convert unchecked server numbers to Int: even finite JSON numbers
    /// may exceed its range and trap. An invalid, present code is not success.
    private static func businessCode(_ payload: [String: Any]) throws -> Int {
        guard let value = payload["error_code"] else { return 0 }
        if let number = value as? NSNumber, CFGetTypeID(number) == CFBooleanGetTypeID() {
            throw MusicError.message("汽水音乐返回了无效的登录错误码，请重新获取二维码。")
        }
        guard let parsed = Self.number(value), parsed >= Double(Int32.min), parsed <= Double(Int32.max), parsed.rounded(.towardZero) == parsed else {
            throw MusicError.message("汽水音乐返回了无效的登录错误码，请重新获取二维码。")
        }
        return Int(parsed)
    }
    private static func status(_ value: Any?) -> String {
        if let text = value as? String { return text.lowercased() }
        if let number = value as? NSNumber { return number.stringValue }
        return ""
    }

}
